name: Create Release

on:
  push:
    tags:
      - 'v*' # Срабатывает при пуше тегов, начинающихся с "v"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем код
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Устанавливаем нужную версию Node.js

      # Шаг 3: Устанавливаем pnpm с использованием официального действия
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '7' # Устанавливаем нужную версию pnpm (например, 7)

      # Шаг 4: Устанавливаем зависимости проекта с помощью pnpm
      - name: Install dependencies
        run: pnpm install

      # Шаг 5: Собираем проект
      - name: Build project
        run: pnpm build

      # Шаг 6: Проверяем содержимое build (отладка)
      - name: List build folder contents
        run: ls -la build # Показывает файлы, которые собрались в папке build

      # Шаг 7: Архивируем содержимое build
      - name: Archive build folder
        run: |
          mkdir release-only
          cp -r build/* release-only/ # Копируем только содержимое build
          cd release-only
          tar -czvf ../build.tar.gz . # Упаковываем содержимое папки release-only
          cd .. # Возвращаемся в корень

      # Шаг 8: Создаём релиз и загружаем архив
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Этот релиз создан автоматически.
          files: build.tar.gz
